services:
  - type: web
    name: ot-mta-pass-list
    env: static
    buildCommand: ""
    staticPublishPath: .
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=3600
      - path: /index.html
        name: Cache-Control  
        value: public, max-age=300
    envVars:
      - key: NODE_ENV
        value: production